// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// setred_loop
List setred_loop(int nlabelednew, int nlabeledold, NumericMatrix D, NumericVector labeled);
RcppExport SEXP _SSLR_setred_loop(SEXP nlabelednewSEXP, SEXP nlabeledoldSEXP, SEXP DSEXP, SEXP labeledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nlabelednew(nlabelednewSEXP);
    Rcpp::traits::input_parameter< int >::type nlabeledold(nlabeledoldSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type labeled(labeledSEXP);
    rcpp_result_gen = Rcpp::wrap(setred_loop(nlabelednew, nlabeledold, D, labeled));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSLR_setred_loop", (DL_FUNC) &_SSLR_setred_loop, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSLR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
