# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setred_loop <- function(nlabelednew, nlabeledold, D, labeled) {
    .Call('_SSLR_setred_loop', PACKAGE = 'SSLR', nlabelednew, nlabeledold, D, labeled)
}

